name: tiger_tools
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.18.0 <3.0.0"

# Add regular dependencies here.
dependencies:
  args: ^2.4.1
  interact: ^2.2.0
  mason: ^0.1.0-dev.41

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0

executables:
  tiger: