include: package:very_good_analysis/analysis_options.3.1.0.yaml

analyzer:
  exclude:
    - build/**
    - mason/**
    - lib/**/*.g.dart
    - pubspec.yaml
linter:
  rules:
    file_names: false
    always_use_package_imports: false
    public_member_api_docs: false
    sort_constructors_first: false
